### PR TITLE
Draft6

### PR DESCRIPTION
**Pull request by ramonsnir**
Can probably be squashed into a single commit (with a nice name), but I wanted to keep my work history until I know it's ready.

This _breaks compatibility_ with previous versions as draft-6 and draft-4 are incompatible.

What do you think?

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e1a1e387f87ddeb031ba7a405b965af7d69bfe4c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 06b7d18f8928a4d0b90efd191687d6628bedb262
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a0b19d66a984438ebfe0a01284e72f6d131afb1b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bb886adfb4d64b5390e821b628f6dce70aaca48d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6e46bcc13a80012c362c4e0c6adda8f1634f7923
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f52c37c8470f203a9c94ae2ca65b114e554b1382
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7099c6936e6cf9e1f93be7e1654e2d2236862cad
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7336a261089bea061f76ed4f3817a734990c3a21
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 27d110ff90bc30aa6ae5760b59e8568fc4333ed9
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f72fdbe4e020fa1fd8ed38cd7cba8df4e38c53d2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a76a12363c82dd4d6aa8d7d9cd0f47ded362692b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9238c631291b730b31a77220227994092ddfff5f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 0571ae5e911673a1de6ab28ae7b7bd4026bdabaa
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/rustless/valico/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e1a1e387f87ddeb031ba7a405b965af7d69bfe4c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 06b7d18f8928a4d0b90efd191687d6628bedb262
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a0b19d66a984438ebfe0a01284e72f6d131afb1b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bb886adfb4d64b5390e821b628f6dce70aaca48d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6e46bcc13a80012c362c4e0c6adda8f1634f7923
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f52c37c8470f203a9c94ae2ca65b114e554b1382
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7099c6936e6cf9e1f93be7e1654e2d2236862cad
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7336a261089bea061f76ed4f3817a734990c3a21
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 27d110ff90bc30aa6ae5760b59e8568fc4333ed9
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f72fdbe4e020fa1fd8ed38cd7cba8df4e38c53d2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a76a12363c82dd4d6aa8d7d9cd0f47ded362692b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9238c631291b730b31a77220227994092ddfff5f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 0571ae5e911673a1de6ab28ae7b7bd4026bdabaa
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ba68ca89750e882cb33a20fed43a0b191280fec3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/rustless/valico/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by s-panferov** [comment]
Awesome work! I'll try not to delay the review.

**Comment by s-panferov** [comment]
@ramonsnir I looked through the request and I don't see anything wrong. I don't use the module by myself now and I cannot check the spec compliance, but I see you invested a lot of time into this, so I count on you.

**Pull request merged**
