### PR TITLE
Update serde to 1.x.y

### PR DESCRIPTION
**Pull request by korczis**
I am opening this PR to open discussion about plans to migrate to serde 1.x.y

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f15c2fcae8a0dbd3ba763cd66198cfd14712dc14
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7f3054012a37ac03745c8273c7ba7ca1e9052164
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/rustless/valico/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by emk** [comment]
@korczis I could also use a version of `valico` that worked with stable `serde`.

**Comment by emk** [comment]
@korczis @camjackson @s-panferov 

Hello! I'm the principal author of `compose_yml` and `cage`, two Docker-related development tools that rely on `valico`. We've been very happy with `valico` for schema validation!

Recently, I updated both tools to use `serde` 1.0. Unfortunately, this meant that I had to disable `valico`, which caused a couple of fairly major regressions in `compose_yml` and `cage`. I would love to get back `valico`'s great validation support.

Is there anything I could do to help get this PR merged (and the corresponding changes to `jsonway` at https://github.com/korczis/jsonway/commit/8a142a0799d9f7afdf5ec1957c1c6791b80d8013)? I'd be happy to devote some engineering time to this.

Also, this would have the advantage of leaving `valico` in a stable state for the long term, because `serde` 1.0 is likely to stick around indefinitely. Also, it would be possible to re-export `serde_json` as `valico::serde_json`, which would allow `valico` to keep working even if `serde` 2.0 is released some day.

Thank you very much for `valico`, and for considering this PR! Please let me know if there's anything at all that I can to smooth the merging process.

**Comment by JordiPolo** [comment]
Really interested on this also, @korczis  any progress?

**Pull request closed without merging**
